name: Distribution

on:
  push:
    branches:
      - "main"
    pull_request:
      - "main"

jobs:
  get-bundle-version:
    if: ${{ github.repository_owner == 'shensven' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Serverless"
    outputs:
      BUNDLE_VERSION: ${{ steps.console-bundle-version.outputs.BUNDLE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Restore private key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" > privateKey.p8

      - name: Console bundle version
        id: console-bundle-version
        env:
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          BUNDLE_VERSION=$(node index.js)
          echo "BUNDLE_VERSION=$BUNDLE_VERSION" >> $GITHUB_OUTPUT
